{% set name = "azure-mgmt-containerservice" %}
{% set version = "22.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 1937c58f65c97b4d516872944dd466fd945f348becc7199f9714dc7d07da634e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - isodate >=0.6.1,<1.0.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.


extra:
  recipe-maintainers:
    - dhirschfeld
    - tim-werner
