{% set name = "azure-mgmt-containerservice" %}
{% set version = "33.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 868583dcdb8a4905de03a84a9b7903d76a1cb59acd9c3736f02bc743b5047c9e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - typing_extensions >=4.6.0
    - typing-extensions >=4.6.0
    - python >=3.8
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.


extra:
  recipe-maintainers:
    - dhirschfeld
    - tim-werner
