{% set name = "azure-mgmt-containerservice" %}
{% set version = "41.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 592c83288d9cb0822ea031d8815d1d30fe30727da6fa7552d1e825c450ecca6a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - msrest >=0.7.1
    - typing_extensions >=4.6.0
    - typing-extensions >=4.6.0
    - python >={{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.6.0
    - isodate >=0.6.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.


extra:
  recipe-maintainers:
    - dhirschfeld
    - tim-werner
