{% set name = "azure-mgmt-containerservice" %}
{% set version = "26.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 069be74aa79ee70a1db4c5cfc68fe91c2064f18cb8c8f9c474ad7ae1df482ee3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0
    - isodate <1.0.0,>=0.6.1

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.


extra:
  recipe-maintainers:
    - dhirschfeld
    - tim-werner
