{% set name = "azure-mgmt-containerservice" %}
{% set version = "40.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 89a6caf507d340df472dc8dcfe217c1e098cdd8e71353db892efc284330e2f8e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - msrest >=0.7.1
    - typing_extensions >=4.6.0
    - typing-extensions >=4.6.0
    - python >={{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.6.0
    - isodate >=0.6.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.containerservice

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Container Service Management Client Library for Python.


extra:
  recipe-maintainers:
    - dhirschfeld
    - tim-werner
